version: '1'
networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 18080:8080
    expose:
      - 18080
    environment:
      TZ: 'Europe/Moscow'
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/social-network?currentSchema=social_network
      SPRING_DATASOURCE_USERNAME: alisa
      SPRING_DATASOURCE_PASSWORD: password1

    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: db
    image: artifactory.raiffeisen.ru/ext-devimage-docker/postgres:12-alpine
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_USER: alisa
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: social-network

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped
