#info:
#  app:
#    name: social-network
#    version: 1.0.0
#server:
#  servlet:
#    context-path: /api/v1
#  forward-headers-strategy: native
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=social_network
    username: postgres
    password:
    hikari:
      schema: social_network
      maximum-pool-size: 50
      minimum-idle: 10

  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      mode: never

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false

#springdoc:
#  api-docs:
#    path: /api/docs
#  packages-to-scan: ru.otus.highload
#  swagger-ui:
#    disable-swagger-default-url: false
#    show-sql: true
#    properties.hibernate:
#      format_sql: true
#      generate_statistics: true
