spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social-network?currentSchema=social_network
    username: alisa
    password: password1
    hikari:
      schema: social_network
      maximum-pool-size: 50
      minimum-idle: 10

  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      mode: never

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
