spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=social_network
    username: postgres
    password:
    hikari:
      schema: social_network
      maximum-pool-size: 50
      minimum-idle: 10

  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      mode: never

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false

  redis:
    host: localhost

  data:
    redis:
      repositories:
        enabled: true

  main:
    allow-bean-definition-overriding: true

app:
  cache:
    redis:
      postsMaxNumberPerUser: 1000
  redis:
    posts:
      prefix: social-network
  rabbit:
    mq:
      login: guest
      password: guest
      systemLogin: guest
      systemPassword: guest
      host: 127.0.0.1
      port: 61613
  websocket:
    topic-prefix: /topic
    queue-prefix: /queue
    ws-endpoint: /ws-endpoint
    application-destination-prefix: /app
  posts:
    executor:
      core-pool-size: 10
      max-pool-size: 20
      keep-alive-seconds: 5
      await-termination-time-seconds: 10
  users:
    executor:
      core-pool-size: 10
      max-pool-size: 20
      keep-alive-seconds: 5
      await-termination-time-seconds: 10
