package ru.otus.highload.configuration

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class WebSecurityInitializer :AbstractSecurityWebApplicationInitializer()